### PR TITLE
Add ability to color irc messages

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Comment by wolfy1339** [comment]
@itslukej care to comment over my code. Everything seems to work with my testing.

**Comment by itslukej** [comment]
Should it be color or colour?

**Comment by wolfy1339** [comment]
I used colour because the name of the file was `colours.py`, I personnaly use color.

**Comment by itslukej** [comment]
should it be changed to color then?

**Comment by wolfy1339** [comment]
Yeah.

**Comment by wolfy1339** [comment]
@itslukej That's done.

**Comment by wolfy1339** [comment]
@itslukej The TravisCI failure was irrelevant. (I restarted the builds, and they pass). The nick was already in use, and the connection timed out.
That raises another issue, maybe kill the tests after a certain time.

**Comment by wolfy1339** [comment]
I am going to merge this now, since you seem onboard with this.

**Pull request merged**
