### PR TITLE
Port changes from #15 into test.py

### PR DESCRIPTION
**Pull request by wolfy1339**
I'll gladly create a wiki entry for this after it is merged

### CODE REVIEW

**Comment by wolfy1339** [comment]
@itslukej Can you open up (allow editing) the README to everybody, so anyone can help document zIRC,. Just like in this case where docs are needed

**Comment by itslukej** [comment]
I don't know if thats possible

**Comment by wolfy1339** [comment]
In the repository settings, uncheck the `Restrict editing to collaborators only.` option

**Comment by itslukej** [comment]
Done

**Pull request merged**
